name: Load Test

on:
  workflow_run:
    workflows: ['VM Deploy NodeBB']
    types:
      - completed
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Setup k6
        uses: grafana/setup-k6-action@v1
      
      - name: Run load test
        uses: grafana/run-k6-action@v1
        with:
          path: test/load-testing/basic-load-test.js
        env:
          BASE_URL: 'http://128.2.220.232:4567/'
